---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: greeting
    commands:
      - export PROJECT_NAME=$(git config --local remote.origin.url | tr '/' '\n' | tail -1)
      - export BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
      - export BINARY_FOLDER_PATH=/home/zong/blog

      # build front-end
      - cd front_end
      - yarn install
      - yarn build
      - cd ..
      - go build .
  # create gitea release
  - name: auto-release
    image: xena/gitea-release:latest
    pull: always
    settings:
      auth_username: guangzong
      changelog_path: ./CHANGELOG.md
      gitea_server: https://gitea.ggeta.com
      gitea_token:
        from_secret: GITEA_TOKEN
    when:
      event:
        - push
      branch:
        - main
