---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

trigger:
  branch:
    - main
  event:
    exclude:
      - tag

steps:
  - name:  prepare front-end build
    commands:
#       build front-end
      - cd front_end
      - yarn install
  - name: bulid front-end
    commands:
      - pwd
      - yarn build

  - name: build back-end
    commands:
      - pwd
      - cd .. 
      - go build .
  # create gitea release
  - name: create release
    environment:
      GITEA_TOKEN:
        from_secret: gitea_token
    commands:
      - pwd
      - export GITEA_NAME=gitea.ggeta.com
      - export BUILD_TIME=$(date +%Y-%m-%d-%H-%M-%S)
      # login use tea
      - echo $GITEA_NAME
      - echo $GITEA_URL$GITEA_NAME
      - echo $GITEA_TOKEN
      - tea login add --token $GITEA_TOKEN --url=https://$GITEA_NAME
      # set as default
      - tea login default $GITEA_NAME
      # create release
      - tea r create --title=ci-build --tag $BUILD_TIME --asset go_blog
